rules:
  security-in-query:
    description: Requires the usage of query parameter for security.
    message: Must add query parameter to in property for security object
    given: $.security.*
    severity: error
    then:
      field: in
      function: enumeration
      functionOptions:
        values:
          - query
