rules:
  response-patch-204-no-body:
    description: Ensures PATCH operations do not have a response body.
    message: A PATCH operation should not have a response body.
    given: $paths.patch.responses.204
    severity: error
    then:
      field: schema
      function: falsy
