rules:
  info-version:
    description: Ensures that all Swaggers have a information object version.
    message: The info object should have a version.
    given: $.info
    severity: error
    formats:
      - oas2
    then:
      field: version
      function: truthy
