rules:
  schema-properties-type:
    description: Ensuring that all schemas properties should have a type.
    message: All schema properties should have type property.
    given: $..properties.*
    severity: warn
    formats:
      - oas3
    then:
      field: type
      function: truthy
