rules:
  response-put-500-status-code:
    description: Ensures PUT operations have a 500 status code response.
    message: A PUT operation should have a 500 status code for the response.
    given: $.paths[*].put.responses
    severity: warn
    formats:
      - oas2
      - oas3
    then:
      field: '500'
      function: truthy
