rules:
  https-only:
    description: Ensures that all APIs are only using HTTPS protocol as a transport.
    message: You must only use HTTPS for the server transport protocol.
    given: $.servers..url
    severity: error
    formats:
      - oas3
    then:
      function: pattern
      functionOptions: null
      match: /^https:/
