rules:
  request-bodies-examples-any-oas3:
    description: Ensures that an example or examples element is always present for each request body.
    message: All request bodies should have example or examples present.
    given: $.paths.*.*.requestBody.content.* # v3
    severity: warn
    formats:
      - oas3
    then:
      function: xor
      functionOptions:
        properties:
          - examples
          - example
