rules:
  response-delete-204-status-code:
    description: Ensures DELETE operations have a 204 status code response.
    message: A DELETE operation should have a 204 status code for the response.
    given: $.paths[*].delete.responses
    severity: warn
    formats:
      - oas2
      - oas2
    then:
      field: '204'
      function: truthy
