rules:
  request-body-on-patch-oas2:
    description: Ensures that PATCH methods have request bodies.
    message: Your PATCH methods should have request bodies.
    given: $.paths.*.patch
    severity: warn
    formats:
      - oas2
    then:
      function: schema
      functionOptions:
        schema:
          $schema: "https://json-schema.org/draft/2020-12/schema"
          required: [parameters]
          properties:
            parameters:
              type: array
              minItems: 1
              contains:
                type: object
                properties:
                  in:
                    type: string
                    pattern: ^body|formData$
                required: [name]
  request-body-on-patch-oas3:
    description: Ensures that PATCH methods have request bodies.
    message: Your PATCH methods should have request bodies.
    given: $.paths.*.patch
    severity: warn
    formats:
      - oas3
    then:
      field: requestBody
      function: truthy
