rules:
  reusable-schema-description:
    description: Ensure all reusable schema should have a description.
    message: All reusable schema should have descriptions.
    given: 
      - $.definitions.*
      - $.components.schemas.*
    severity: warn
    formats:
      - oas2
      - oas3
    then:
      field: description
      function: truthy
