rules:
  info-license-url:
    description: Ensures that all OpenAPIs have a information object license url.
    message: The info object should have a license url.
    given: $.info.license
    severity: warn
    formats:
      - oas2
      - oas3
    then:
      field: url
      function: truthy
