rules:
  schema-type:
    description: Ensuring that all schema have a type property.
    message: All schema should have a type property.
    given: $.definitions.*
    severity: error
    formats:
      - oas2
    then:
      field: type
      function: truthy
