rules:
  security-applied-to-operations:
    description: Requires security to be applied to all operations.
    message: Each operation must have a security property.
    given: $.paths.*.*
    severity: error
    then:
      field: security
      function: truthy
