rules:
  schema-required:
    description: Ensuring that all schema have a required property.
    message: All of your schema need to have a required property.
    given: $.definitions.*
    severity: warn
    formats:
      - oas2
    then:
      field: required
      function: truthy
