rules:
  security-scheme-oauth:
    description: Requires the usage of OAuth for security scheme.
    message: Must add OAuth implicit for security scheme.
    given: $
    severity: error
    formats:
      - oas3
    then:
      field: $.components.securitySchemes.[*].type
      function: truthy
