rules:
  info-description:
    description: Ensures that all OpenAPIs have a information description.
    message: The info object should have a description.
    given: $.info
    severity: warn
    formats:
      - oas2
      - oas3
    then:
      field: description
      function: truthy
