id: info-contact
specification: openapi
level: error
reason: |
  Defining contact information is a must have because it ensures someone owns the API and 
  it ensures the consumers know who to contact if there are interested to use it or in case of problem. 
description: |
  Ensures that all APIs have contact information.
message: 
rules:
  - rule: rules/info-contact.openapi-v20.spectral-v6.yaml
    specificationVersions: [ "2.0" ]
    linter: spectral
    linterVersions: [ "6" ]
  - rule: rules/info-contact.openapi-v3X.spectral-v6.yaml
    specificationVersions: [ "3.0", "3.1" ]
    linter: spectral
    linterVersions: [ "6" ]
  - rule: rules/info-contact.openapi-vXX.spectral-v6.yaml
    specificationVersions: [ "universal" ]
    linter: spectral
    linterVersions: [ "6" ]
samples:
  - type: valid
    document: documentation/info-contact.valid.openapi-v20.yaml
    specificationVersion: "2.0"
  - type: valid
    document: documentation/info-contact.valid.openapi-v30.yaml
    specificationVersion: "3.0"
  - type: valid
    document: documentation/info-contact.valid.openapi-v31.yaml
    specificationVersion: "3.1"
  - type: invalid
    document: documentation/info-contact.invalid.openapi-v20.yaml
    specificationVersion: "2.0"
  - type: invalid
    document: documentation/info-contact.invalid.openapi-v30.yaml
    specificationVersion: "3.0"
  - type: invalid
    document: documentation/info-contact.invalid.openapi-v31.yaml
    specificationVersion: "3.1"
