rules:
  response-get-200-media-type:
    description: >-
      Ensuring GET operations have an application/json media type for 200
      responses.
    message: >-
      A GET operation should have an application/json media type for 200
      response.
    given: $paths.get.responses.200.content
    severity: error
    then:
      field: application/json
      function: truthy
