rules:
  info-title-in-kebab-case:
    description: Ensures that all Swaggers information title are in Kebab case.
    message: The info object title needs to be in Kebab case.
    given: $.info.title
    severity: error
    formats:
      - oas2
      - oas2
    then:
      function: pattern
      functionOptions:
        match: ^[a-z][a-z0-9\-]*$
