rules:
  tags-object:
    description: Ensuring that there are tags being applied.
    message: You should have a central tags object.
    given: $
    severity: error
    then:
      field: tags
      function: truthy
