rules:
  response-put-204-no-body:
    description: Ensures PUT operations do not have a response body.
    message: A PUT operation should not have a response body.
    given: $paths.put.responses.204
    severity: error
    then:
      field: schema
      function: falsy
