rules:
  response-patch-500-status-code:
    description: Ensures PATCH operations have a 500 status code response.
    message: A PATCH operation should have a 500 status code for the response.
    given: $.paths[*].patch.responses
    severity: warn
    formats:
      - oas2
      - oas3
    then:
      field: '500'
      function: truthy
