rules:
  response-post-201-status-code:
    description: Ensures POST operations have a 201 status code response.
    message: A POST operation should have a 201 status code for the response.
    given: $.paths[*].post.responses
    severity: warn
    formats:
      - oas2
    then:
      field: '201'
      function: truthy
