rules:
  schema-description:
    description: Ensure all schema properties should have a description.
    message: All schema should have descriptions.
    given: $.definitions.*
    severity: warn
    formats:
      - oas2
    then:
      field: description
      function: truthy
