rules:
  response-get-500-status-code:
    description: Ensures GET operations have a 500 status code response.
    message: A GET operation should have a 500 status code for the response.
    given: $.paths[*].get.responses
    severity: warn
    formats:
      - oas2
      - oas3
    then:
      field: '500'
      function: truthy
