rules:
  schema-names-snake-case:
    description: Ensure all schema names are snake case.
    message: Schema names should be snake case.
    given: $.components.schemas
    severity: error
    then:
      field: '@key'
      function: casing
      functionOptions:
        type: snake
