rules:
  responses-examples:
    description: Ensuring all responses have examples defined.
    message: All your responses need to have examples defined.
    given: $..responses..[?(@property !== 'properties' && @.examples)]
    severity: error
    then:
      function: schemaPath
      functionOptions:
        field: $.examples.*.value
        schemaPath: $.schema
