rules:
  operations-summary:
    description: Ensures that each of the operations for an API have a summary.
    message: All of your operations need summaries.
    given: $.paths.*[get,post,patch,put,delete]
    severity: error
    then:
      - field: summary
        function: truthy
