rules:
  request-body-on-post:
    description: Ensures that POST methods have request bodies.
    message: Your POST methods should have request bodies.
    given: $.paths.*.post.parameters.*
    severity: error
    then:
      field: in
      function: enumeration
      functionOptions:
        values:
          - query
          - header
          - path
          - body
