rules:
  request-body-on-post-oas3:
    description: Ensures that POST methods have request bodies.
    message: Your POST methods should have request bodies.
    given: $.paths.*.post
    severity: warn
    formats:
      - oas3
    then:
      field: requestBody
      function: truthy
