rules:
  operations-summary-period-none:
    description: >-
      Ensures that each of the operations summaries do not have an ending
      period.
    message: Your operations summaries should not end with a period.
    given: $.paths[*][*].summary
    severity: error
    then:
      function: pattern
      functionOptions:
        notMatch: \.$
