rules:
  responses-example-any-oas2:
    description: Ensuring all responses have examples defined.
    message: All your responses need to have examples defined.
    given: $.paths.*.*.responses.*
    severity: warn
    formats:
      - oas2
    then:
      field: examples
      function: truthy