rules:
  info-license:
    description: Ensures that all OpenAPIs have a information object license.
    message: The info object should have a license.
    given: $.info
    severity: error
    formats:
      - oas3
    then:
      field: license
      function: truthy
