rules:
  operations-description:
    description: Ensures that each of the operations have a description.
    message: Your operations all need descriptions.
    given: $.paths.*[get,post,patch,put,delete,options,head,trace]
    severity: warn
    formats:
      - oas2
      - oas3
    then:
      - field: description
        function: truthy
