swagger: "2.0"
info:
  title: an API title
  version: "1.0"
paths:
  /resources:
    post:
      parameters:
        - in: header
          name: Header-Name
          type: string
      responses:
        '201':
          description: a success response
