rules:
  version-semantic:
    description: Ensuring that semantic versioning is being used.
    message: You need to provide a semantic version.
    given: $.info.version
    severity: error
    then:
      function: pattern
      functionOptions: null
      match: ^[0-9]+.[0-9]+.[0-9]+(-[a-z0-9+.-]+)?
