rules:
  schema-properties-allowed-integer-format:
    description: Requires integer properties to have a format of int32 or int64.
    message: Type format should be be int32 or int64.
    given: $..properties.[?(@.type=="integer")]
    severity: hint
    formats:
      - oas3
    then:
      field: format
      function: enumeration
      functionOptions:
        values:
          - int32
          - int64
