rules:
  no-trailing-slash-on-paths:
    description: Ensures that there are no trailing slashes on paths.
    message: There should be no trailing slashes on paths.
    given: $.paths.*~
    severity: error
    formats:
      - oas2
      - oas3
    then:
      function: pattern
      functionOptions:
        notMatch: .+\/$
