rules:
  request-body-on-post-oas2:
    description: Ensures that POST methods have request bodies.
    message: Your POST methods should have request bodies.
    given: $.paths.*.post
    severity: warn
    formats:
      - oas2
    then:
      function: schema
      functionOptions:
        schema:
          $schema: "https://json-schema.org/draft/2020-12/schema"
          required: [parameters]
          properties:
            parameters:
              type: array
              minItems: 1
              contains:
                type: object
                properties:
                  in:
                    type: string
                    pattern: ^body|formData$
                required: [name]