rules:
  info-x-audience:
    description: Ensures that all Swaggers have a information object audience extension.
    message: The info object should have an audience extension.
    given: $.info
    severity: error
    then:
      field: x-audience
      function: truthy
