rules:
  request-body-on-put:
    description: Ensures that PUT methods have request bodies.
    message: Your PUT methods should have request bodies.
    given: $.paths.*.put
    severity: warn
    formats:
      - oas2
      - oas3
    then:
      function: schema
      functionOptions:
        schema:
          $schema: "https://json-schema.org/draft/2020-12/schema"
          oneOf:
            - required: [requestBody]
            - required: [parameters]
              properties:
                parameters:
                  type: array
                  minItems: 1
                  contains:
                    type: object
                    properties:
                      in:
                        type: string
                        pattern: ^body|formData$
                    required: [name]