rules:
  request-body-on-put-oas3:
    description: Ensures that PUT methods have request bodies.
    message: Your PUT methods should have request bodies.
    given: $.paths.*.put
    severity: warn
    formats:
      - oas3
    then:
      field: requestBody
      function: truthy
