rules:
  security-scheme-oauth2-password:
    description: Requires the usage of OAuth2 password for security scheme.
    message: Must add OAuth2 password implicit for security scheme.
    given: $
    severity: error
    formats:
      - oas3
    then:
      field: $.components.securitySchemes.[*].flows.password
      function: truthy
