rules:
  info-contact-url:
    description: Ensures that all APIs have contact URL.
    message: API must have a contact URL available.
    given: $.info.contact
    severity: error
    formats:
      - oas2
      - oas3
    then:
      field: url
      function: truthy
