rules:
  request-body-examples-components:
    description: >-
      Check request bodies examples to ensure that they only have references to
      components.
    message: Request bodies examples should only reference components.
    given:
      - $..requestBody.content..*.examples.$ref
    severity: error
    then:
      function: pattern
      functionOptions:
        match: '#/components/'
