rules:
  schema-properties-descriptions-length:
    description: Ensure that schema descriptions aren't too long.
    message: The schema description length needs to be less than 250 characters.
    given: $..properties.*
    severity: warn
    formats:
      - oas3
    then:
      field: description
      function: length
      functionOptions:
        max: 250
