rules:
  http-authorized-callback-methods:
    documentationUrl: https://www.rfc-editor.org/rfc/rfc9110#name-overview
    description: Any http methods specified should be one of the supported list.
    message: "{{property}} is not a supported method: {{error}}"
    given: 
      - $.paths..callbacks[*][*].*~
    severity: warn
    formats:
      - oas3
    then:
      function: pattern
      functionOptions:
        match: /^(options|get|head|post|put|delete|trace|connect|patch)$/i