rules:
  have-request-body-examples:
    description: Ensures that a example is always present for each request body.
    message: All request bodies should have an example present.
    given: $.paths.*.*.requestBody..[?(@.items)][?(@.type == 'object')]
    severity: error
    formats:
      - oas3
    then:
      - field: example
        function: truthy
