rules:
  schema-properties-names-pascal-case:
    description: Ensuring that schema property names are pascal case.
    message: All schema property names should be pascal case.
    given: $..properties.*
    severity: error
    then:
      field: '@key'
      function: casing
      functionOptions:
        type: pascal
