rules:
  no-empty-paths:
    description: Ensures that there are no empty paths.
    message: There should be no empty paths.
    given: $.paths.*~
    severity: error
    then:
      function: pattern
      functionOptions:
        notMatch: //
