rules:
  schema-names-pascal-case:
    description: Ensure all schema names are pascal case.
    message: Schema names should be pascal case.
    given: $.definitions
    severity: error
    then:
      field: '@key'
      function: casing
      functionOptions:
        type: pascal
