rules:
  schema-properties-names-snake-case:
    description: Ensuring that schema property names are snake case.
    message: All schema property names should be snake case.
    given: $..properties.*
    severity: error
    then:
      field: '@key'
      function: casing
      functionOptions:
        type: snake
