rules:
  schema-names-camel-case:
    description: Ensure all schema names are camel case.
    message: Schema names should be camel case.
    given: $.components.schemas
    severity: error
    then:
      field: '@key'
      function: casing
      functionOptions:
        type: camel
