rules:
  responses-schema-components:
    description: >-
      Check response schema to ensure that they only have references to
      components.
    message: Response schema should only reference components.
    given:
      - $..responses.*.content..*.schema.$ref
    severity: error
    then:
      function: pattern
      functionOptions:
        match: '#/components/'
