rules:
  response-get-200-status-code:
    description: Ensures GET operations have a 200 status code response.
    message: A GET operation should have a 200 status code for the response.
    given: $.paths[*].get.responses
    severity: warn
    formats:
      - oas2
      - oas3
    then:
      field: '200'
      function: truthy
