rules:
  info-title-max-length:
    description: >-
      Ensures that all Swaggers information titles are not longer than 50
      characters.
    message: The info object title should not be more than 50 characters.
    given: $.info
    severity: error
    formats:
      - oas2
    then:
      field: title
      function: length
      functionOptions:
        max: 50
