rules:
  schema-properties-names-camel-case:
    description: Ensuring that schema property names are camel case.
    message: All schema property names should be camel case.
    given: $.definitions.properties.*
    severity: error
    then:
      field: '@key'
      function: casing
      functionOptions:
        type: camel
