rules:
  schema-names-length:
    description: Ensure schema names should be no more than 25 characters.
    message: All schema names should be less than 25 characters.
    given: $.definitions
    severity: error
    then:
      field: '@key'
      function: length
      functionOptions:
        max: 25
