rules:
  produce-json-media-type:
    description: Ensures that application/json media types are able to be produced.
    message: The APIs should be able to produce application/json media types.
    given: $..produces.*
    severity: error
    then:
      function: schema
      functionOptions:
        schema:
          type: string
          enum:
            - application/json
