rules:
  schema-properties-define-number-boundaries:
    description: Ensures that all number properties have boundaries defined.
    message: Numeric types need to have a minimum and maximum property defined.
    given:
      - $..properties.[?(@.type=="number")]
      - $..properties.[?(@.type=="integer")]
    severity: warn
    formats:
      - oas3
    then:
      - field: maximum
        function: defined
      - field: minimum
        function: defined
