rules:
  no-request-body-on-get:
    description: Ensures that GET methods do not have request bodies.
    message: Your GET methods should not have request bodies.
    given: $.paths.*.get
    severity: error
    then:
      field: requestBody
      function: falsy
