rules:
  consume-json-media-type:
    description: Ensures that application/json media types are able to be consumed.
    message: The APIs should be able to consume application/json media types.
    given: $..consumes.*
    severity: error
    then:
      function: schema
      functionOptions:
        schema:
          type: string
          enum:
            - application/json
