rules:
  schema-properties-allowed-number-format:
    description: Ensure only allowed number formats.
    message: >-
      You must have format property of decimal32, decimal64, float, double,
      decimal128
    given: $..properties.[?(@.type=="number")]
    severity: hint
    formats:
      - oas3
    then:
      field: format
      function: enumeration
      functionOptions:
        values:
          - decimal32
          - decimal64
          - float
          - double
          - decimal128
