rules:
  request-body-json-media-type-on-put:
    description: Ensures that PUT methods have request bodies.
    message: Your PUT methods should have request bodies.
    given: $.paths.*.put[requestBody].content
    severity: error
    then:
      field: application/json
      function: truthy
