rules:
  schema-properties-descriptions:
    description: Ensure that all schemas properties should have a description.
    message: All schema properties should have descriptions.
    given: $..properties.*
    severity: warn
    formats:
      - oas2
      - oas3
    then:
      field: description
      function: truthy
