rules:
  no-response-body-on-204:
    description: Ensures that no 204 No Content response has a body.
    message: A 204 No Content response can't have a body.
    given: $.paths.*.*.responses.204
    severity: error
    formats:
      - oas2
      - oas3
    then:
      - field: schema # oas 2
        function: falsy
      - field: content # oas 3
        function: falsy
